# MacOS dir = ~/Library/Application Support/lazygit
os:
  # To be able to use it with nvim
  edit: "floatterm"

gui:
  # Use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - "#94e2d5"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#94e2d5"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: never
    pager: diff-so-fancy
